### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by remyahalza** [rohitrajv5/pimcore-bundle-azure-blob-sync#1]
I got error " Could not find a version of package rohitrajv5/pimcore-bundle-azure-blob-sync matching your minimum-stability (stable). Require it wit
  h an explicit version constraint allowing its desired stability."

 when use  composer require rohitrajv5/pimcore-bundle-azure-blob-sync

**Comment by rohitrajv5** [comment]
This issue has been resolved
